// GENERATED by pod_latest.sh — do not hand-edit.
// WALL-E always reads the NEWEST pod revision on disk. Today that is rev013-double-shear.
pod_latest_rev  = "rev013-double-shear";
pod_latest_file = "../archive/rev013-double-shear/apollo_track_pod_rev013.scad";
include <../archive/rev013-double-shear/apollo_track_pod_rev013.scad>
