#!/usr/bin/env bash
# ============================================================================
#  Write pod_latest.scad, which points at the NEWEST pod revision on disk.
#
#    ./pod_latest.sh
#
#  WALL-E must always be checked against the latest pod model, not against a
#  revision someone pinned by hand months ago. This script picks the highest
#  archive/revNNN-*/apollo_track_pod_revNNN.scad and writes a one-line include
#  for it. render_all.sh runs it before anything else.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")"
latest=$(ls -d ../archive/rev*/apollo_track_pod_rev*.scad 2>/dev/null | sort -V | tail -1)
[ -n "$latest" ] || { echo "!! no pod model found under ../archive"; exit 1; }
rev=$(basename "$(dirname "$latest")")
cat > pod_latest.scad <<EOF
// GENERATED by pod_latest.sh — do not hand-edit.
// WALL-E always reads the NEWEST pod revision on disk. Today that is $rev.
pod_latest_rev  = "$rev";
pod_latest_file = "$latest";
include <$latest>
EOF
echo "   pod_latest.scad -> $latest"
